Theme Selector update
FilipeMSouza/rpg-handouts pull request #22
Opened 2024-05-05 20:38 UTC by FilipeMSouza

This PR add a all new style theme to this project. sorry but I didn't take scree shots previously so this is how it's working now

### dark

  - ![image](https://github.com/FilipeMSouza/rpg-handouts/assets/33045754/4bad8c3c-0fe5-4717-bee9-e7d65aea30dc)

  - ![image](https://github.com/FilipeMSouza/rpg-handouts/assets/33045754/f655e30a-16c7-4263-96f8-92951eaf465a)
  
  - ![image](https://github.com/FilipeMSouza/rpg-handouts/assets/33045754/252222c6-3977-4662-82b1-1dc24bd08da9)
  
### light

  - ![image](https://github.com/FilipeMSouza/rpg-handouts/assets/33045754/91ff0a36-15f1-4615-8680-8cedd7f9ddc2)

  - ![image](https://github.com/FilipeMSouza/rpg-handouts/assets/33045754/797cfb74-7338-4e26-82ce-97fc4e51a092)

  - ![image](https://github.com/FilipeMSouza/rpg-handouts/assets/33045754/fd92c823-d62b-4865-9999-343795f0e91c)

2024-05-07 22:15 UTC, h80r requested changes
Quando acessei a página o botão de mudança de tema estava desaparecido, conforme anexo abaixo:
<img width="654" alt="image" src="https://github.com/FilipeMSouza/rpg-handouts/assets/60087690/af7c9cf5-6779-452a-aa9b-4cd3868f8daa">
- É interessante observar se não podemos passar esse componente dentro do ThemeProvider e evitar problemas.

Além disso, acredito que a _navbar_ precisa acompanhar a mudança de cor do tema

2024-05-07 22:15 UTC, h80r commented on src/app/layout.tsx
> +    if (typeof window === 'undefined') return dark;
Pra não esquecermos desse fix, caso ocorra novamente, sugiro extrair a validação como um hook
```ts
const isVercelLoading = () => typeof window === 'undefined';
```

e salvar num arquivo de _hook_ próprio, fazendo o ajuste aqui:
```suggestion
    if (isVercelLoading()) return dark;
```

2024-05-07 22:15 UTC, h80r commented on src/app/layout.tsx
> +    }
Como é feito o return no caso do _if_, o _else_ imediatamente se torna desnecessário.
Do mesmo modo, como é uma validação breve, e também não se encontra em um operador ternário (que resultaria no encadeamento de ternários, paia), o ideal seria implementar o _return_ diretamente.

```suggestion
    return theme === DARK_THEME ? dark : light;
```

2024-05-07 22:15 UTC, h80r commented on src/consts.ts
> +export const DARK_THEME = 'dark-theme';
Incluir uma constante pro tema claro

2024-05-07 22:15 UTC, h80r commented on src/style/Theme.styled.ts
> +  name: 'light-theme',
Substituir o nome em string pela constante

2024-05-07 22:15 UTC, h80r commented on src/style/Theme.styled.ts
> +  name: 'dark-theme',
Substituir o nome em string pela constante

2024-05-08 03:07 UTC, h80r commented on src/components/molecules/ThemeSelector/ThemeSelctor.tsx
> +import React, { useMemo, useState } from 'react';
O nome do arquivo possui um _typo_

2024-05-13 22:02 UTC, h80r requested changes
Ótimo trabalho, só um pequeno ajuste pendente.

2024-05-13 22:02 UTC, h80r commented on src/components/Organism/Navbar/Navbar.tsx
> +import { NavbarBody } from '@/components/Organism/Navbar/style';
Padronizar o título das pastas, os outros dois estão _full_ `camel_case` e essa pasta tá `PascalCase` (Organism)

2024-05-13 23:27 UTC, FilipeMSouza commented on src/components/Organism/Navbar/Navbar.tsx
> +import { NavbarBody } from '@/components/Organism/Navbar/style';
vou subir agr

2024-05-19 22:49 UTC, h80r approved these changes
LGTM ✅

2024-05-21 00:45 UTC, merged